language: go

sudo: required
services:
    - docker

install: 
    - true

script: 
    - docker build -t thethingsindustries/protoc .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push thethingsindustries/protoc
